# Generated by Django 2.1.2 on 2019-01-04 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exchange_fees', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('content', models.TextField(max_length=200)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debtcalculatorapp.Currency')),
                ('debtors', models.ManyToManyField(related_name='debtor', to='debtcalculatorapp.Member')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lender', to='debtcalculatorapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debtcalculatorapp.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtcalculatorapp.Profile'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debtcalculatorapp.Profile'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtcalculatorapp.Profile'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='secondary_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debtcalculatorapp.Currency'),
        ),
    ]
