# Generated by Django 2.1.2 on 2019-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtcalculatorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
